import type { CalendarSettings } from '../utils/settings';
import { DEFAULT_SETTINGS } from '../utils/settings';
import type { CalendarThemeCatalogEntry } from './calendarThemeTypes';

const SERIF_STACK = '"Frank Ruhl Libre", "David Libre", Georgia, "Times New Roman", serif';
const CLASSIC_STACK = '"David Libre", David, "Times New Roman", serif';
const SANS_STACK = '"Rubik", "Assistant", system-ui, -apple-system, "Segoe UI", sans-serif';
const HAND_STACK = '"Kalam", "Segoe Print", "Bradley Hand", cursive';

/** סולם גדלים בתא: לועזי > עברי > אירועים > זמני שבת/חג (כל ערכת נושא; `wall_old` וכו׳ יכולים לדרוס). */
const CELL_TYPO_LADDER: Pick<
  CalendarSettings,
  'gregDayFontPx' | 'hebDayFontPx' | 'eventTitleFontPx' | 'shabbatTimesFontPx'
> = {
  gregDayFontPx: 1,
  hebDayFontPx: 1,
  eventTitleFontPx: 1,
  shabbatTimesFontPx: 1,
};

function patch(p: Partial<CalendarSettings>): Partial<CalendarSettings> {
  return { ...CELL_TYPO_LADDER, ...p };
}

/** Visual themes: merged as `{ ...DEFAULT_SETTINGS, ...entry.patch, ...preserved }`. */
export const CALENDAR_THEME_CATALOG: CalendarThemeCatalogEntry[] = [
  {
    id: 'classic_torani',
    nameHe: 'קלאסי־תורני',
    blurbHe: 'רקע דמוי קלף, מסגרת כפולה, פונט ספרותי',
    previewCss: 'linear-gradient(145deg,#f5e6c8 0%,#e8d4b8 45%,#d4bc98 100%)',
    cellBorder: 'double',
    patch: patch({
      headerLayoutStyle: 'seamless',
      fontFamily: SERIF_STACK,
      fontWeight: 400,
      headerBarBg: 'linear-gradient(180deg,#faf6ef 0%,#ebe1d0 100%)',
      headerBarBorderColor: '#8b7355',
      headerBarBorderWidthPx: 2,
      headerBarTitleColor: '#3d2914',
      headerBarSubtitleColor: '#6b5344',
      headerHebMonthBg: 'rgba(255,252,245,0.95)',
      headerHebMonthBorderColor: '#8b7355',
      headerGregMonthBorderColor: '#a89070',
      calendarCanvasFill: '#fbf6ec',
      gridShellBg: 'rgba(255,250,240,0.92)',
      gridBorderColor: '#c4a574',
      gridWeekdayHeaderBg: '#f3ead8',
      gridWeekdayHeaderTextColor: '#4a3728',
      gridWeekdayHeaderBorderBottomColor: '#bfa67a',
      cellBorderWidthPx: 2,
      cellBorderColor: '#9a7b52',
      cellBorderStyle: 'double',
      cellCornerRadiusPx: 0,
      eventBg: '#e0ecf7',
      shabbatBg: '#fff3d6',
      todayBg: '#e8eef8',
      canvasBorderColor: '#a89070',
    }),
  },
  {
    id: 'retro_yeshivish',
    nameHe: 'רטרו־ישיבתי (וינייטה)',
    blurbHe: 'מסגרת מעוטרת לכותרת, קווים קלאסיים (מדומה), סריף',
    previewCss: 'linear-gradient(160deg,#f7efe1 0%,#eadcc6 45%,#c8b08a 100%)',
    cellBorder: 'double',
    patch: patch({
      headerLayoutStyle: 'seamless',
      fontFamily: SERIF_STACK,
      fontWeight: 400,
      headerBarBg: 'radial-gradient(circle at 50% 50%, rgba(255,255,255,0.92) 0%, rgba(245,235,220,0.92) 55%, rgba(225,210,185,0.92) 100%)',
      headerBarBorderColor: '#7a5c3a',
      headerBarBorderWidthPx: 3,
      headerBarTitleColor: '#2b1b0f',
      headerBarSubtitleColor: '#5b4632',
      headerHebMonthBg: 'rgba(255,255,255,0.92)',
      headerHebMonthBorderColor: '#7a5c3a',
      headerGregMonthBorderColor: '#9a7b52',
      calendarCanvasFill: '#fbf6ec',
      gridShellBg: 'rgba(255,250,240,0.92)',
      gridBorderWidthPx: 3,
      gridBorderColor: '#c4a574',
      gridWeekdayHeaderBg: '#f3ead8',
      gridWeekdayHeaderTextColor: '#3b2a1b',
      gridWeekdayHeaderBorderBottomWidthPx: 2,
      gridWeekdayHeaderBorderBottomColor: '#bfa67a',
      cellBorderWidthPx: 2,
      cellBorderColor: '#9a7b52',
      cellBorderStyle: 'double',
      cellCornerRadiusPx: 0,
      canvasBorderColor: '#a89070',
    }),
  },
  {
    id: 'minimal_clean_nolines',
    nameHe: 'מינימליסטי נקי (בלי קווים)',
    blurbHe: 'ללא גבולות תאים, ימי שבוע מודגשים, “רשת דמיונית”',
    previewCss: 'linear-gradient(180deg,#ffffff 0%,#f8fafc 100%)',
    cellBorder: 'thin',
    patch: patch({
      headerLayoutStyle: 'minimal_text',
      fontFamily: SANS_STACK,
      fontWeight: 400,
      showCellBorders: false,
      gridBorderWidthPx: 0,
      gridBorderColor: '#ffffff',
      cellBorderWidthPx: 0,
      cellBorderColor: '#ffffff',
      cellBorderStyle: 'solid',
      gridWeekdayHeaderBg: 'transparent',
      gridWeekdayHeaderTextColor: '#0f172a',
      gridWeekdayHeaderBorderBottomWidthPx: 0,
      gridWeekdayHeaderFontWeight: 700,
      calendarCanvasFill: '#ffffff',
      gridShellBg: '#ffffff',
      eventBg: 'transparent',
      shabbatBg: 'rgba(2,132,199,0.06)',
      todayBg: 'rgba(37,99,235,0.08)',
      canvasBorderWidthPx: 0,
      canvasBorderColor: '#ffffff',
    }),
  },
  {
    id: 'pocket_compact',
    nameHe: 'מבנה “כיס” (קומפקטי)',
    blurbHe: 'פורמט צר/ארוך, טקסט קטן, מתאים ליומן קטן',
    previewCss: 'linear-gradient(180deg,#ffffff 0%,#eef2ff 100%)',
    cellBorder: 'thin',
    patch: patch({
      pdfPagePreset: 'A5',
      pdfOrientation: 'portrait',
      headerLayoutStyle: 'seamless',
      headerBarHeightPx: 56,
      headerBarMarginBottomPx: 8,
      headerHebMonthFontPx: 18,
      headerGregMonthFontPx: 12,
      fontFamily: SANS_STACK,
      fontWeight: 400,
      fontSizePx: 12,
      gregDayFontPx: 11,
      hebDayFontPx: 10,
      eventTitleFontPx: 9,
      shabbatTimesFontPx: 8,
      gridWeekdayHeaderHeightPx: 26,
      gridWeekdayHeaderFontPx: 12,
      gridWeekdayHeaderFontWeight: 700,
      canvasPaddingPx: 10,
      canvasPaddingTopPx: 18,
      gridBorderWidthPx: 1,
      cellBorderWidthPx: 1,
      cellCornerRadiusPx: 6,
      canvasBorderWidthPx: 1,
    }),
  },
  {
    id: 'combined_header',
    nameHe: 'כותרת משולבת (עברי/לועזי יחד)',
    blurbHe: 'החודשים מוצגים זה לצד זה בפס הכותרת (מראה מודרני)',
    previewCss: 'linear-gradient(90deg,#ffffff 0%,#f1f5f9 100%)',
    cellBorder: 'thin',
    patch: patch({
      headerLayoutStyle: 'floating',
      fontFamily: SANS_STACK,
      fontWeight: 400,
      headerBarBg: '#ffffff',
      headerBarBorderColor: '#e2e8f0',
      headerBarBorderWidthPx: 1,
      headerHebMonthBg: '#f8fafc',
      headerHebMonthBorderWidthPx: 1,
      headerHebMonthBorderColor: '#e2e8f0',
      headerGregMonthBorderWidthPx: 1,
      headerGregMonthBorderColor: '#e2e8f0',
      headerGregMonthBg: '#f8fafc',
    }),
  },
  {
    id: 'double_headerbar',
    nameHe: 'פס כותרת כפול',
    blurbHe: 'כותרת חודש + פס ימי שבוע צמוד ומודגש',
    previewCss: 'linear-gradient(180deg,#f8fafc 0%,#ffffff 100%)',
    cellBorder: 'thin',
    patch: patch({
      headerLayoutStyle: 'seamless',
      headerBarHeightPx: 70,
      headerBarMarginBottomPx: 0,
      gridWeekdayHeaderHeightPx: 30,
      gridWeekdayHeaderBg: '#f8fafc',
      gridWeekdayHeaderBorderBottomWidthPx: 2,
      gridWeekdayHeaderBorderBottomColor: '#e2e8f0',
      gridWeekdayHeaderFontWeight: 700,
      gridWeekdayHeaderTextColor: '#0f172a',
    }),
  },
  {
    id: 'modern_soft',
    nameHe: 'Modern Soft (פינות מעוגלות)',
    blurbHe: 'מראה אפליקטיבי: פינות מעוגלות, קווים עדינים',
    previewCss: 'linear-gradient(160deg,#ecfeff 0%,#e0f2fe 45%,#eff6ff 100%)',
    cellBorder: 'rounded',
    patch: patch({
      fontFamily: SANS_STACK,
      fontWeight: 400,
      cellCornerRadiusPx: 14,
      cellBorderWidthPx: 1,
      cellBorderColor: '#cbd5e1',
      gridBorderWidthPx: 1,
      gridBorderColor: '#cbd5e1',
      headerBarRadiusPx: 18,
      headerBarBg: 'rgba(255,255,255,0.9)',
      gridShellBg: 'rgba(255,255,255,0.85)',
      eventBg: '#e0f2fe',
      shabbatBg: '#fef9c3',
      todayBg: '#dbeafe',
    }),
  },
  {
    id: 'overlay_header',
    nameHe: 'כותרת צפה (Overlay)',
    blurbHe: 'פס הכותרת חצי שקוף, יושב “מעל” הרשת',
    previewCss: 'linear-gradient(180deg,#ffffff 0%,#f1f5f9 100%)',
    cellBorder: 'thin',
    patch: patch({
      headerLayoutStyle: 'floating',
      headerBarBg: 'rgba(255,255,255,0.55)',
      headerBarBorderWidthPx: 0,
      headerBarMarginBottomPx: 8,
      gridWeekdayHeaderBg: 'rgba(248,250,252,0.55)',
      gridShellBg: 'rgba(255,255,255,0.82)',
    }),
  },
  {
    id: 'handdrawn_art',
    nameHe: 'סגנון “כתב יד” (אמנותי)',
    blurbHe: 'פונט כתב יד + קווים רכים (מדומה)',
    previewCss: 'linear-gradient(140deg,#fff7ed 0%,#ffedd5 45%,#fde68a 100%)',
    cellBorder: 'thin',
    patch: patch({
      fontFamily: HAND_STACK,
      fontWeight: 400,
      cellBorderWidthPx: 2,
      cellBorderColor: '#c4b5fd',
      gridBorderWidthPx: 2,
      gridBorderColor: '#c4b5fd',
      headerBarBg: 'rgba(255,255,255,0.85)',
      headerBarBorderColor: '#c4b5fd',
      calendarCanvasFill: '#fff7ed',
      gridShellBg: 'rgba(255,255,255,0.9)',
      cellCornerRadiusPx: 10,
    }),
  },
  {
    id: 'compact_torani',
    nameHe: 'קומפקטי תורני',
    blurbHe: 'מקסימום שטח לטקסט בתא + פס כותרת דק',
    previewCss: 'linear-gradient(180deg,#ffffff 0%,#f8fafc 100%)',
    cellBorder: 'thin',
    patch: patch({
      headerLayoutStyle: 'seamless',
      fontFamily: SERIF_STACK,
      fontWeight: 400,
      headerBarHeightPx: 52,
      headerBarMarginBottomPx: 6,
      headerHebMonthFontPx: 18,
      headerGregMonthFontPx: 12,
      gridWeekdayHeaderHeightPx: 26,
      gridWeekdayHeaderFontPx: 12,
      gridWeekdayHeaderFontWeight: 700,
      canvasPaddingPx: 10,
      canvasPaddingTopPx: 18,
      layoutFillHeight: true,
      pdfExportCellHeightPx: 96,
    }),
  },
  {
    id: 'vintage_typography',
    nameHe: 'הדור הישן (טיפוגרפיה וינטג׳)',
    blurbHe: 'מסגרת כפולה ללוח + דגש טיפוגרפי ליום העברי',
    previewCss: 'linear-gradient(145deg,#f7f3ea 0%,#e9e1d4 45%,#cdbfa9 100%)',
    cellBorder: 'double',
    patch: patch({
      headerLayoutStyle: 'seamless',
      fontFamily: CLASSIC_STACK,
      fontWeight: 700,
      calendarCanvasFill: '#faf6ef',
      gridShellBg: 'rgba(255,250,240,0.92)',
      canvasBorderWidthPx: 3,
      canvasBorderColor: '#3b2a1b',
      gridBorderWidthPx: 3,
      gridBorderColor: '#3b2a1b',
      cellBorderStyle: 'double',
      cellBorderWidthPx: 2,
      cellBorderColor: '#3b2a1b',
      // Typography emphasis: small gregorian, large hebrew, center focus.
      gregDayFontPx: 12,
      hebDayFontPx: 18,
      eventTitleFontPx: 10,
      shabbatTimesFontPx: 9,
      headerBarBg: 'linear-gradient(180deg,#f4efe6 0%,#e6dccb 100%)',
      headerBarBorderColor: '#3b2a1b',
      headerBarBorderWidthPx: 2,
      headerBarTitleColor: '#1f2937',
      headerBarSubtitleColor: '#374151',
    }),
  },
  {
    id: 'clean_slate_magazine',
    nameHe: 'מגזין מודרני (Clean Slate)',
    blurbHe: 'כותרת שקופה + סאנס נקי + מספרים גדולים ודקים',
    previewCss: 'linear-gradient(180deg,#ffffff 0%,#f8fafc 100%)',
    cellBorder: 'thin',
    patch: patch({
      headerLayoutStyle: 'minimal_text',
      fontFamily: SANS_STACK,
      fontWeight: 400,
      headerBarBg: 'transparent',
      headerBarBorderWidthPx: 0,
      headerBarBorderColor: 'transparent',
      calendarCanvasFill: '#ffffff',
      gridShellBg: '#ffffff',
      gridBorderWidthPx: 1,
      gridBorderColor: '#e5e7eb',
      cellBorderStyle: 'solid',
      cellBorderWidthPx: 1,
      cellBorderColor: 'rgba(15,23,42,0.10)',
      // Light “magazine” typography: large gregorian, slim feel via lighter weight + smaller hebrew.
      gregDayFontPx: 18,
      hebDayFontPx: 11,
      eventTitleFontPx: 10,
      shabbatTimesFontPx: 9,
      gridWeekdayHeaderBg: 'transparent',
      gridWeekdayHeaderBorderBottomWidthPx: 1,
      gridWeekdayHeaderBorderBottomColor: 'rgba(15,23,42,0.10)',
    }),
  },
  {
    id: 'torah_scholar_yeshiva',
    nameHe: 'לוח ישיבתי (Torah Scholar)',
    blurbHe: 'כותרת בסגנון וינייטה + רקע אפור בהיר + דגש פרשה/חג',
    previewCss: 'linear-gradient(160deg,#f3f4f6 0%,#e5e7eb 55%,#d1d5db 100%)',
    cellBorder: 'double',
    patch: patch({
      headerLayoutStyle: 'seamless',
      fontFamily: SERIF_STACK,
      fontWeight: 400,
      headerBarBg: 'linear-gradient(180deg,#f3f4f6 0%,#e5e7eb 100%)',
      headerBarBorderColor: '#111827',
      headerBarBorderWidthPx: 1,
      headerBarTitleColor: '#111827',
      headerBarSubtitleColor: '#374151',
      calendarCanvasFill: '#f9fafb',
      gridShellBg: 'rgba(255,255,255,0.92)',
      gridBorderWidthPx: 2,
      gridBorderColor: '#111827',
      cellBorderStyle: 'double',
      cellBorderWidthPx: 2,
      cellBorderColor: '#111827',
      shabbatBg: 'rgba(250,204,21,0.10)',
      eventBg: 'rgba(59,130,246,0.08)',
      todayBg: 'rgba(16,185,129,0.08)',
    }),
  },
  {
    id: 'dark_mode_tech',
    nameHe: 'הייטק (Dark Mode Tech)',
    blurbHe: 'כהה, פינות מעוגלות, קונטרסט גבוה',
    previewCss: 'linear-gradient(160deg,#0b1220 0%,#111827 45%,#0f172a 100%)',
    cellBorder: 'rounded',
    patch: patch({
      headerLayoutStyle: 'seamless',
      fontFamily: SANS_STACK,
      fontWeight: 600,
      calendarCanvasFill: '#0b1220',
      gridShellBg: 'rgba(17,24,39,0.92)',
      canvasBorderColor: '#334155',
      gridBorderColor: '#334155',
      gridWeekdayHeaderBg: '#0f172a',
      gridWeekdayHeaderTextColor: '#e5e7eb',
      headerBarBg: '#0f172a',
      headerBarBorderColor: '#334155',
      headerBarTitleColor: '#ffffff',
      headerBarSubtitleColor: '#cbd5e1',
      cellBorderStyle: 'solid',
      cellBorderWidthPx: 1,
      cellBorderColor: 'rgba(148,163,184,0.25)',
      cellCornerRadiusPx: 10,
      eventBg: 'rgba(56,189,248,0.18)',
      shabbatBg: 'rgba(250,204,21,0.16)',
      todayBg: 'rgba(129,140,248,0.18)',
    }),
  },
  {
    id: 'wall_calendar_classic',
    nameHe: 'לוח קיר מסורתי (Wall Classic)',
    blurbHe: 'רשת עבה ובולטת + פס כותרת בצבע אחיד חזק',
    previewCss: 'linear-gradient(180deg,#f8fafc 0%,#e2e8f0 100%)',
    cellBorder: 'thin',
    patch: patch({
      headerLayoutStyle: 'seamless',
      fontFamily: CLASSIC_STACK,
      fontWeight: 700,
      headerBarBg: '#2563eb',
      headerBarBorderColor: '#1e40af',
      headerBarBorderWidthPx: 2,
      headerBarTitleColor: '#ffffff',
      headerBarSubtitleColor: '#dbeafe',
      calendarCanvasFill: '#ffffff',
      gridShellBg: '#ffffff',
      canvasBorderWidthPx: 3,
      canvasBorderColor: '#0f172a',
      gridBorderWidthPx: 3,
      gridBorderColor: '#0f172a',
      cellBorderWidthPx: 2,
      cellBorderColor: '#0f172a',
      cellBorderStyle: 'solid',
      // “Big gregorian” feel.
      gregDayFontPx: 20,
      hebDayFontPx: 11,
    }),
  },
  {
    id: 'zen_japanese_minimal',
    nameHe: 'מינימליזם יפני (Zen)',
    blurbHe: 'קווים כמעט שקופים + הרבה חלל לבן',
    previewCss: 'linear-gradient(180deg,#ffffff 0%,#fafafa 100%)',
    cellBorder: 'thin',
    patch: patch({
      headerLayoutStyle: 'minimal_text',
      fontFamily: SANS_STACK,
      fontWeight: 400,
      headerBarBg: 'transparent',
      headerBarBorderWidthPx: 0,
      calendarCanvasFill: '#ffffff',
      gridShellBg: '#ffffff',
      gridBorderWidthPx: 1,
      gridBorderColor: 'rgba(2,6,23,0.08)',
      cellBorderWidthPx: 1,
      cellBorderColor: 'rgba(2,6,23,0.06)',
      cellBorderStyle: 'solid',
      gridWeekdayHeaderBg: 'transparent',
      gridWeekdayHeaderBorderBottomColor: 'rgba(2,6,23,0.06)',
      gridWeekdayHeaderBorderBottomWidthPx: 1,
      // Airy typography.
      gregDayFontPx: 16,
      hebDayFontPx: 10,
      eventTitleFontPx: 9,
      shabbatTimesFontPx: 8,
    }),
  },
  {
    id: 'executive_torah',
    nameHe: 'אלגנט תורני (Executive)',
    blurbHe: 'קווים חום־כהה/זהב, מראה יוקרתי וקריא',
    previewCss: 'linear-gradient(145deg,#fff7ed 0%,#fed7aa 45%,#a16207 120%)',
    cellBorder: 'thin',
    patch: patch({
      headerLayoutStyle: 'seamless',
      fontFamily: SERIF_STACK,
      fontWeight: 400,
      headerBarBg: 'linear-gradient(180deg,#fff7ed 0%,#ffedd5 100%)',
      headerBarBorderColor: '#7c2d12',
      headerBarBorderWidthPx: 2,
      headerBarTitleColor: '#7c2d12',
      headerBarSubtitleColor: '#9a3412',
      calendarCanvasFill: '#fff7ed',
      gridShellBg: 'rgba(255,255,255,0.92)',
      gridBorderColor: '#7c2d12',
      gridBorderWidthPx: 2,
      cellBorderColor: 'rgba(124,45,18,0.55)',
      cellBorderWidthPx: 1,
      cellBorderStyle: 'solid',
    }),
  },
  {
    id: 'book_layout_bw',
    nameHe: 'עימוד לספר (שחור-לבן)',
    blurbHe: 'מותאם להדפסה נקייה בלי מילויים, היררכיה טיפוגרפית',
    previewCss: 'linear-gradient(180deg,#ffffff 0%,#f8fafc 100%)',
    cellBorder: 'thin',
    patch: patch({
      headerLayoutStyle: 'minimal_text',
      fontFamily: '"Noto Serif Hebrew", "David Libre", serif',
      fontWeight: 400,
      calendarCanvasFill: '#ffffff',
      gridShellBg: '#ffffff',
      headerBarBg: 'transparent',
      headerBarBorderWidthPx: 0,
      gridBorderWidthPx: 2,
      gridBorderColor: '#111827',
      cellBorderWidthPx: 1,
      cellBorderColor: '#111827',
      cellBorderStyle: 'solid',
      eventBg: 'transparent',
      shabbatBg: 'transparent',
      todayBg: 'transparent',
      canvasBorderWidthPx: 2,
      canvasBorderColor: '#111827',
    }),
  },
  {
    id: 'floral_vintage',
    nameHe: 'פרחוני עתיק',
    blurbHe: 'ורוד עמום, עיטורי פינות רכים',
    previewCss: 'linear-gradient(160deg,#fce7f3 0%,#fbcfe8 40%,#f9a8d4 100%)',
    cellBorder: 'rounded',
    patch: patch({
      fontFamily: SERIF_STACK,
      fontWeight: 400,
      headerBarBg: 'linear-gradient(90deg,#fff1f7 0%,#fce7f3 100%)',
      headerBarBorderColor: '#f472b6',
      headerBarTitleColor: '#831843',
      headerBarSubtitleColor: '#9d174d',
      headerHebMonthBg: 'rgba(255,255,255,0.9)',
      headerHebMonthBorderColor: '#f9a8d4',
      headerGregMonthBorderColor: '#fbcfe8',
      calendarCanvasFill: '#fdf2f8',
      gridShellBg: 'rgba(255,247,252,0.9)',
      gridBorderColor: '#f9a8d4',
      gridWeekdayHeaderBg: '#fce7f3',
      gridWeekdayHeaderTextColor: '#831843',
      gridWeekdayHeaderBorderBottomColor: '#f472b6',
      cellBorderWidthPx: 1,
      cellBorderColor: '#f9a8d4',
      cellBorderStyle: 'solid',
      cellCornerRadiusPx: 12,
      headerBarRadiusPx: 20,
      eventBg: '#e0f2fe',
      shabbatBg: '#fef9c3',
      todayBg: '#fce7f3',
      canvasBorderColor: '#f472b6',
    }),
  },
  {
    id: 'minimal',
    nameHe: 'מודרני נקי',
    blurbHe: 'קווים דקים, הרבה לבן, סאנס',
    previewCss: 'linear-gradient(180deg,#ffffff 0%,#f8fafc 100%)',
    cellBorder: 'thin',
    patch: patch({
      headerLayoutStyle: 'minimal_text',
      fontFamily: SANS_STACK,
      fontWeight: 400,
      headerBarBg: '#ffffff',
      headerBarBorderColor: '#e2e8f0',
      headerBarBorderWidthPx: 1,
      headerBarTitleColor: '#0f172a',
      headerBarSubtitleColor: '#64748b',
      headerHebMonthBg: '#f8fafc',
      headerHebMonthBorderWidthPx: 1,
      headerHebMonthBorderColor: '#e2e8f0',
      headerGregMonthBorderWidthPx: 0,
      calendarCanvasFill: '#ffffff',
      gridShellBg: '#ffffff',
      gridBorderWidthPx: 1,
      gridBorderColor: '#e2e8f0',
      gridWeekdayHeaderBg: '#f8fafc',
      gridWeekdayHeaderTextColor: '#475569',
      gridWeekdayHeaderBorderBottomWidthPx: 1,
      gridWeekdayHeaderBorderBottomColor: '#e2e8f0',
      cellBorderWidthPx: 1,
      cellBorderColor: '#e2e8f0',
      cellBorderStyle: 'solid',
      cellCornerRadiusPx: 0,
      headerBarRadiusPx: 8,
      eventBg: '#f1f5f9',
      shabbatBg: '#fafaf9',
      todayBg: '#eff6ff',
      canvasBorderColor: '#e2e8f0',
    }),
  },
  {
    id: 'mizrach',
    nameHe: 'עדות המזרח',
    blurbHe: 'טורקיז, זהב, מרוקאי־אנדלוסי',
    previewCss: 'linear-gradient(135deg,#0d9488 0%,#14b8a6 35%,#ca8a04 100%)',
    cellBorder: 'thin',
    patch: patch({
      fontFamily: SERIF_STACK,
      fontWeight: 400,
      headerBarBg: 'linear-gradient(90deg,#115e59 0%,#0f766e 50%,#0d9488 100%)',
      headerBarBorderColor: '#ca8a04',
      headerBarTitleColor: '#fefce8',
      headerBarSubtitleColor: '#ccfbf1',
      headerHebMonthBg: 'rgba(15,118,110,0.85)',
      headerHebMonthTextColor: '#fefce8',
      headerHebMonthBorderColor: '#facc15',
      headerGregMonthTextColor: '#fefce8',
      headerGregMonthBorderColor: '#facc15',
      headerGregMonthBg: 'rgba(15,118,110,0.5)',
      calendarCanvasFill: '#ecfdf5',
      gridShellBg: 'rgba(240,253,250,0.95)',
      gridBorderColor: '#2dd4bf',
      gridWeekdayHeaderBg: '#ccfbf1',
      gridWeekdayHeaderTextColor: '#134e4a',
      gridWeekdayHeaderBorderBottomColor: '#14b8a6',
      cellBorderWidthPx: 1,
      cellBorderColor: '#99f6e4',
      cellBorderStyle: 'solid',
      cellCornerRadiusPx: 4,
      eventBg: '#cffafe',
      shabbatBg: '#fef9c3',
      todayBg: '#e0f2fe',
      canvasBorderColor: '#0d9488',
    }),
  },
  {
    id: 'chassidic',
    nameHe: 'חסידי',
    blurbHe: 'כחול עמוק, זהב, כבד',
    previewCss: 'linear-gradient(160deg,#1e3a5f 0%,#312e81 50%,#ca8a04 100%)',
    cellBorder: 'double',
    patch: patch({
      headerLayoutStyle: 'right_block',
      fontFamily: CLASSIC_STACK,
      fontWeight: 400,
      headerBarBg: 'linear-gradient(180deg,#1e293b 0%,#312e81 100%)',
      headerBarBorderColor: '#ca8a04',
      headerBarTitleColor: '#fefce8',
      headerBarSubtitleColor: '#cbd5e1',
      headerHebMonthBg: 'rgba(30,41,59,0.9)',
      headerHebMonthTextColor: '#fef08a',
      headerHebMonthBorderColor: '#eab308',
      headerGregMonthTextColor: '#fefce8',
      headerGregMonthBorderColor: '#eab308',
      calendarCanvasFill: '#0f172a',
      gridShellBg: 'rgba(30,41,59,0.92)',
      gridBorderColor: '#64748b',
      gridWeekdayHeaderBg: '#1e293b',
      gridWeekdayHeaderTextColor: '#e2e8f0',
      gridWeekdayHeaderBorderBottomColor: '#ca8a04',
      cellBorderWidthPx: 2,
      cellBorderColor: '#94a3b8',
      cellBorderStyle: 'double',
      cellCornerRadiusPx: 0,
      eventBg: '#dbeafe',
      shabbatBg: '#ffedd5',
      todayBg: '#e0e7ff',
      canvasBorderColor: '#ca8a04',
    }),
  },
  {
    id: 'family_fun',
    nameHe: 'ילדים / משפחתי',
    blurbHe: 'צבעוני, פינות מעוגלות',
    previewCss: 'linear-gradient(120deg,#fef08a 0%,#fda4af 40%,#93c5fd 100%)',
    cellBorder: 'rounded',
    patch: patch({
      headerLayoutStyle: 'centered_pill',
      fontFamily: SANS_STACK,
      fontWeight: 400,
      headerBarBg: 'linear-gradient(90deg,#fef9c3 0%,#fce7f3 50%,#dbeafe 100%)',
      headerBarBorderColor: '#f472b6',
      headerBarTitleColor: '#7c2d12',
      headerBarSubtitleColor: '#c2410c',
      headerHebMonthBg: '#ffffff',
      headerHebMonthBorderColor: '#38bdf8',
      headerGregMonthBorderColor: '#f472b6',
      calendarCanvasFill: '#fffbeb',
      gridShellBg: 'rgba(255,255,255,0.95)',
      gridBorderColor: '#fbbf24',
      gridWeekdayHeaderBg: '#fef3c7',
      gridWeekdayHeaderTextColor: '#9a3412',
      gridWeekdayHeaderBorderBottomColor: '#fb923c',
      cellBorderWidthPx: 2,
      cellBorderColor: '#fcd34d',
      cellBorderStyle: 'solid',
      cellCornerRadiusPx: 16,
      headerBarRadiusPx: 24,
      eventBg: '#dbeafe',
      shabbatBg: '#fef9c3',
      todayBg: '#fce7f3',
      canvasBorderColor: '#f472b6',
    }),
  },
  {
    id: 'wall_old',
    nameHe: 'לוח קיר ישן',
    blurbHe: 'כותרות גדולות, מינימום גרפיקה',
    previewCss: 'linear-gradient(180deg,#f8fafc 0%,#e2e8f0 100%)',
    cellBorder: 'thin',
    patch: patch({
      headerLayoutStyle: 'seamless',
      fontFamily: CLASSIC_STACK,
      fontWeight: 400,
      headerBarHeightPx: 92,
      headerHebMonthFontPx: 28,
      headerGregMonthFontPx: 18,
      gregDayFontPx: 18,
      hebDayFontPx: 18,
      eventTitleFontPx: 14,
      shabbatTimesFontPx: 12,
      headerBarBg: '#f1f5f9',
      headerBarBorderColor: '#64748b',
      headerBarTitleColor: '#0f172a',
      headerBarSubtitleColor: '#475569',
      headerHebMonthBg: '#ffffff',
      headerHebMonthBorderWidthPx: 1,
      calendarCanvasFill: '#f8fafc',
      gridShellBg: '#ffffff',
      gridBorderWidthPx: 1,
      gridBorderColor: '#cbd5e1',
      gridWeekdayHeaderBg: '#e2e8f0',
      gridWeekdayHeaderFontPx: 15,
      gridWeekdayHeaderTextColor: '#0f172a',
      cellBorderWidthPx: 1,
      cellBorderColor: '#94a3b8',
      cellBorderStyle: 'solid',
      cellCornerRadiusPx: 0,
      eventBg: '#e2e8f0',
      shabbatBg: '#fef3c7',
      todayBg: '#dbeafe',
      canvasBorderColor: '#64748b',
    }),
  },
  {
    id: 'nature_il',
    nameHe: 'טבע ארץ־ישראלי',
    blurbHe: 'ירוק־חום, אדמה ושמיים',
    previewCss: 'linear-gradient(180deg,#ecfccb 0%,#86efac 40%,#4d7c0f 100%)',
    cellBorder: 'thin',
    patch: patch({
      fontFamily: SANS_STACK,
      fontWeight: 400,
      headerBarBg: 'linear-gradient(90deg,#ecfccb 0%,#d9f99d 100%)',
      headerBarBorderColor: '#4d7c0f',
      headerBarTitleColor: '#14532d',
      headerBarSubtitleColor: '#3f6212',
      headerHebMonthBg: 'rgba(255,255,255,0.92)',
      headerHebMonthBorderColor: '#65a30d',
      calendarCanvasFill: '#f7fee7',
      gridShellBg: 'rgba(255,255,255,0.88)',
      gridBorderColor: '#84cc16',
      gridWeekdayHeaderBg: '#ecfccb',
      gridWeekdayHeaderTextColor: '#365314',
      gridWeekdayHeaderBorderBottomColor: '#a3e635',
      cellBorderWidthPx: 1,
      cellBorderColor: '#bbf7d0',
      cellBorderStyle: 'solid',
      cellCornerRadiusPx: 6,
      eventBg: '#dbeafe',
      shabbatBg: '#fef9c3',
      todayBg: '#dcfce7',
      canvasBorderColor: '#4d7c0f',
    }),
  },
  {
    id: 'dark_mode',
    nameHe: 'מצב לילה',
    blurbHe: 'רקע כהה, ניגודיות גבוהה',
    previewCss: 'linear-gradient(180deg,#020617 0%,#1e293b 100%)',
    cellBorder: 'thin',
    patch: patch({
      fontFamily: SANS_STACK,
      fontWeight: 400,
      headerBarBg: 'linear-gradient(180deg,#0f172a 0%,#1e293b 100%)',
      headerBarBorderColor: '#334155',
      headerBarTitleColor: '#f8fafc',
      headerBarSubtitleColor: '#94a3b8',
      headerHebMonthBg: 'rgba(15,23,42,0.9)',
      headerHebMonthTextColor: '#f8fafc',
      headerHebMonthBorderColor: '#475569',
      headerGregMonthTextColor: '#f8fafc',
      headerGregMonthBorderColor: '#64748b',
      headerGregMonthBg: 'rgba(30,41,59,0.6)',
      calendarCanvasFill: '#020617',
      gridShellBg: 'rgba(15,23,42,0.85)',
      gridBorderColor: '#334155',
      gridWeekdayHeaderBg: '#1e293b',
      gridWeekdayHeaderTextColor: '#e2e8f0',
      gridWeekdayHeaderBorderBottomColor: '#475569',
      cellBorderWidthPx: 1,
      cellBorderColor: '#334155',
      cellBorderStyle: 'solid',
      cellCornerRadiusPx: 6,
      eventBg: '#c7d2fe',
      shabbatBg: '#fde68a',
      todayBg: '#bae6fd',
      canvasBorderColor: '#475569',
    }),
  },
  {
    id: 'executive',
    nameHe: 'יוקרתי',
    blurbHe: 'שחור, אפור, זהב',
    previewCss: 'linear-gradient(135deg,#0a0a0a 0%,#27272a 40%,#ca8a04 100%)',
    cellBorder: 'thin',
    patch: patch({
      headerLayoutStyle: 'right_block',
      fontFamily: SANS_STACK,
      fontWeight: 400,
      headerBarBg: 'linear-gradient(90deg,#09090b 0%,#18181b 100%)',
      headerBarBorderColor: '#ca8a04',
      headerBarTitleColor: '#fafaf9',
      headerBarSubtitleColor: '#a1a1aa',
      headerHebMonthBg: 'rgba(24,24,27,0.95)',
      headerHebMonthTextColor: '#fef08a',
      headerHebMonthBorderColor: '#eab308',
      headerGregMonthTextColor: '#fafaf9',
      headerGregMonthBorderColor: '#a16207',
      calendarCanvasFill: '#fafafa',
      gridShellBg: 'rgba(255,255,255,0.95)',
      gridBorderColor: '#d4d4d8',
      gridWeekdayHeaderBg: '#f4f4f5',
      gridWeekdayHeaderTextColor: '#18181b',
      gridWeekdayHeaderBorderBottomColor: '#ca8a04',
      cellBorderWidthPx: 1,
      cellBorderColor: '#d4d4d8',
      cellBorderStyle: 'solid',
      cellCornerRadiusPx: 4,
      eventBg: '#e0e7ff',
      shabbatBg: '#fef9c3',
      todayBg: '#e4e4e7',
      canvasBorderColor: '#27272a',
    }),
  },
  {
    id: 'watercolor',
    nameHe: 'אקוורל',
    blurbHe: 'כתמי צבע עדינים',
    previewCss: 'linear-gradient(120deg,#e0f2fe 0%,#fce7f3 50%,#fef3c7 100%)',
    cellBorder: 'rounded',
    patch: patch({
      headerLayoutStyle: 'centered_pill',
      fontFamily: SERIF_STACK,
      fontWeight: 400,
      headerBarBg: 'linear-gradient(120deg,#f0f9ff 0%,#fdf2f8 100%)',
      headerBarBorderColor: '#7dd3fc',
      headerBarTitleColor: '#0c4a6e',
      headerBarSubtitleColor: '#0369a1',
      headerHebMonthBg: 'rgba(255,255,255,0.85)',
      headerHebMonthBorderColor: '#f9a8d4',
      calendarCanvasFill: '#f8fafc',
      gridShellBg: 'rgba(255,255,255,0.75)',
      gridBorderColor: '#bae6fd',
      gridWeekdayHeaderBg: '#e0f2fe',
      gridWeekdayHeaderTextColor: '#0c4a6e',
      gridWeekdayHeaderBorderBottomColor: '#7dd3fc',
      cellBorderWidthPx: 1,
      cellBorderColor: '#e0e7ff',
      cellBorderStyle: 'solid',
      cellCornerRadiusPx: 14,
      headerBarRadiusPx: 22,
      eventBg: '#e0f2fe',
      shabbatBg: '#fef3c7',
      todayBg: '#fce7f3',
      canvasBorderColor: '#93c5fd',
    }),
  },
  {
    id: 'handwriting',
    nameHe: 'כתב יד',
    blurbHe: 'פונט כתב יד, רקע דף',
    previewCss: 'linear-gradient(180deg,#fffef7 0%,#fefce8 50%,#fef9c3 100%)',
    cellBorder: 'rounded',
    patch: patch({
      fontFamily: HAND_STACK,
      fontWeight: 400,
      headerBarBg: 'repeating-linear-gradient(0deg,#fffbeb,#fffbeb 23px,#fef3c7 23px,#fef3c7 24px)',
      headerBarBorderColor: '#d6d3d1',
      headerBarTitleColor: '#44403c',
      headerBarSubtitleColor: '#78716c',
      headerHebMonthBg: 'rgba(255,255,255,0.9)',
      headerHebMonthBorderColor: '#a8a29e',
      calendarCanvasFill: '#fffbeb',
      gridShellBg: 'rgba(255,253,245,0.92)',
      gridBorderColor: '#d6d3d1',
      gridWeekdayHeaderBg: '#fef3c7',
      gridWeekdayHeaderTextColor: '#57534e',
      gridWeekdayHeaderBorderBottomColor: '#d6d3d1',
      cellBorderWidthPx: 1,
      cellBorderColor: '#e7e5e4',
      cellBorderStyle: 'solid',
      cellCornerRadiusPx: 10,
      eventBg: '#e0f2fe',
      shabbatBg: '#ffedd5',
      todayBg: '#fef08a',
      canvasBorderColor: '#a8a29e',
    }),
  },
];

export const STYLE_PACK_IDS = new Set([
  'retro_yeshivish',
  'minimal_clean_nolines',
  'pocket_compact',
  'combined_header',
  'double_headerbar',
  'modern_soft',
  'overlay_header',
  'handdrawn_art',
  'compact_torani',
  'vintage_typography',
  'clean_slate_magazine',
  'torah_scholar_yeshiva',
  'dark_mode_tech',
  'wall_calendar_classic',
  'zen_japanese_minimal',
  'executive_torah',
  'book_layout_bw',
]);

// (legacy note) theme application used to preserve a large key list; color themes no longer need it.

const COLOR_THEME_KEYS: (keyof CalendarSettings)[] = [
  'headerBarBg',
  'headerBarBorderColor',
  'headerBarBorderWidthPx',
  'headerBarTitleColor',
  'headerBarSubtitleColor',
  'headerHebMonthBg',
  'headerHebMonthTextColor',
  'headerHebMonthBorderColor',
  'headerHebMonthBorderWidthPx',
  'headerGregMonthBg',
  'headerGregMonthTextColor',
  'headerGregMonthBorderColor',
  'headerGregMonthBorderWidthPx',
  'calendarCanvasFill',
  'gridShellBg',
  'gridBorderColor',
  'gridWeekdayHeaderBg',
  'gridWeekdayHeaderTextColor',
  'gridWeekdayHeaderBorderBottomColor',
  'cellBorderColor',
  'eventBg',
  'shabbatBg',
  'todayBg',
  'canvasBorderColor',
  'backgroundOpacity',
];

function pickColorPatch(patch: Partial<CalendarSettings>): Partial<CalendarSettings> {
  const out: Partial<CalendarSettings> = {};
  for (const k of COLOR_THEME_KEYS) {
    const v = patch[k];
    if (v !== undefined) (out as any)[k] = v;
  }
  return out;
}

export function applyDesignThemeId(current: CalendarSettings, themeId: string): CalendarSettings {
  if (themeId === 'default') {
    // Reset colors to defaults but keep current layout/typography/content.
    return {
      ...current,
      ...pickColorPatch(DEFAULT_SETTINGS),
      designThemeId: 'default',
    } as CalendarSettings;
  }
  const entry = CALENDAR_THEME_CATALOG.find((t) => t.id === themeId);
  if (!entry) {
    return { ...current, ...pickColorPatch(DEFAULT_SETTINGS), designThemeId: 'default' };
  }
  // Color themes should only influence palette, not layout/typography (handled by style packs).
  return {
    ...current,
    ...pickColorPatch(entry.patch),
    designThemeId: themeId,
  } as CalendarSettings;
}

export function applyStylePackId(current: CalendarSettings, stylePackId: string): CalendarSettings {
  if (!stylePackId || stylePackId === 'default') {
    return { ...current, stylePackId: 'default' };
  }
  const entry = CALENDAR_THEME_CATALOG.find((t) => t.id === stylePackId);
  if (!entry) return { ...current, stylePackId: 'default' };
  // Apply structural patch on top of current (keep colors/theme as-is).
  return {
    ...current,
    ...entry.patch,
    stylePackId,
  } as CalendarSettings;
}

export function getThemeEntry(themeId: string): CalendarThemeCatalogEntry | undefined {
  return CALENDAR_THEME_CATALOG.find((t) => t.id === themeId);
}
