import type { CalendarSettings } from '../utils/settings';
import { DEFAULT_SETTINGS } from '../utils/settings';
import type { CalendarThemeCatalogEntry } from './calendarThemeTypes';

const SERIF_STACK = '"Frank Ruhl Libre", "David Libre", Georgia, "Times New Roman", serif';
const CLASSIC_STACK = '"David Libre", David, "Times New Roman", serif';
const SANS_STACK = '"Rubik", "Assistant", system-ui, -apple-system, "Segoe UI", sans-serif';
const HAND_STACK = '"Kalam", "Segoe Print", "Bradley Hand", cursive';

/** סולם גדלים בתא: לועזי > עברי > אירועים > זמני שבת/חג (כל ערכת נושא; `wall_old` וכו׳ יכולים לדרוס). */
const CELL_TYPO_LADDER: Pick<
  CalendarSettings,
  'gregDayFontPx' | 'hebDayFontPx' | 'eventTitleFontPx' | 'shabbatTimesFontPx'
> = {
  gregDayFontPx: 17,
  hebDayFontPx: 15,
  eventTitleFontPx: 14,
  shabbatTimesFontPx: 12,
};

function patch(p: Partial<CalendarSettings>): Partial<CalendarSettings> {
  return { ...CELL_TYPO_LADDER, ...p };
}

/** Visual themes: merged as `{ ...DEFAULT_SETTINGS, ...entry.patch, ...preserved }`. */
export const CALENDAR_THEME_CATALOG: CalendarThemeCatalogEntry[] = [
  {
    id: 'classic_torani',
    nameHe: 'קלאסי־תורני',
    blurbHe: 'רקע דמוי קלף, מסגרת כפולה, פונט ספרותי',
    previewCss: 'linear-gradient(145deg,#f5e6c8 0%,#e8d4b8 45%,#d4bc98 100%)',
    cellBorder: 'double',
    patch: patch({
      headerLayoutStyle: 'seamless',
      fontFamily: SERIF_STACK,
      fontWeight: 600,
      headerBarBg: 'linear-gradient(180deg,#faf6ef 0%,#ebe1d0 100%)',
      headerBarBorderColor: '#8b7355',
      headerBarBorderWidthPx: 2,
      headerBarTitleColor: '#3d2914',
      headerBarSubtitleColor: '#6b5344',
      headerHebMonthBg: 'rgba(255,252,245,0.95)',
      headerHebMonthBorderColor: '#8b7355',
      headerGregMonthBorderColor: '#a89070',
      calendarCanvasFill: '#fbf6ec',
      gridShellBg: 'rgba(255,250,240,0.92)',
      gridBorderColor: '#c4a574',
      gridWeekdayHeaderBg: '#f3ead8',
      gridWeekdayHeaderTextColor: '#4a3728',
      gridWeekdayHeaderBorderBottomColor: '#bfa67a',
      cellBorderWidthPx: 2,
      cellBorderColor: '#9a7b52',
      cellBorderStyle: 'double',
      cellCornerRadiusPx: 0,
      eventBg: '#e0ecf7',
      shabbatBg: '#fff3d6',
      todayBg: '#e8eef8',
      canvasBorderColor: '#a89070',
    }),
  },
  {
    id: 'floral_vintage',
    nameHe: 'פרחוני עתיק',
    blurbHe: 'ורוד עמום, עיטורי פינות רכים',
    previewCss: 'linear-gradient(160deg,#fce7f3 0%,#fbcfe8 40%,#f9a8d4 100%)',
    cellBorder: 'rounded',
    patch: patch({
      fontFamily: SERIF_STACK,
      fontWeight: 600,
      headerBarBg: 'linear-gradient(90deg,#fff1f7 0%,#fce7f3 100%)',
      headerBarBorderColor: '#f472b6',
      headerBarTitleColor: '#831843',
      headerBarSubtitleColor: '#9d174d',
      headerHebMonthBg: 'rgba(255,255,255,0.9)',
      headerHebMonthBorderColor: '#f9a8d4',
      headerGregMonthBorderColor: '#fbcfe8',
      calendarCanvasFill: '#fdf2f8',
      gridShellBg: 'rgba(255,247,252,0.9)',
      gridBorderColor: '#f9a8d4',
      gridWeekdayHeaderBg: '#fce7f3',
      gridWeekdayHeaderTextColor: '#831843',
      gridWeekdayHeaderBorderBottomColor: '#f472b6',
      cellBorderWidthPx: 1,
      cellBorderColor: '#f9a8d4',
      cellBorderStyle: 'solid',
      cellCornerRadiusPx: 12,
      headerBarRadiusPx: 20,
      eventBg: '#e0f2fe',
      shabbatBg: '#fef9c3',
      todayBg: '#fce7f3',
      canvasBorderColor: '#f472b6',
    }),
  },
  {
    id: 'minimal',
    nameHe: 'מודרני נקי',
    blurbHe: 'קווים דקים, הרבה לבן, סאנס',
    previewCss: 'linear-gradient(180deg,#ffffff 0%,#f8fafc 100%)',
    cellBorder: 'thin',
    patch: patch({
      headerLayoutStyle: 'minimal_text',
      fontFamily: SANS_STACK,
      fontWeight: 600,
      headerBarBg: '#ffffff',
      headerBarBorderColor: '#e2e8f0',
      headerBarBorderWidthPx: 1,
      headerBarTitleColor: '#0f172a',
      headerBarSubtitleColor: '#64748b',
      headerHebMonthBg: '#f8fafc',
      headerHebMonthBorderWidthPx: 1,
      headerHebMonthBorderColor: '#e2e8f0',
      headerGregMonthBorderWidthPx: 0,
      calendarCanvasFill: '#ffffff',
      gridShellBg: '#ffffff',
      gridBorderWidthPx: 1,
      gridBorderColor: '#e2e8f0',
      gridWeekdayHeaderBg: '#f8fafc',
      gridWeekdayHeaderTextColor: '#475569',
      gridWeekdayHeaderBorderBottomWidthPx: 1,
      gridWeekdayHeaderBorderBottomColor: '#e2e8f0',
      cellBorderWidthPx: 1,
      cellBorderColor: '#e2e8f0',
      cellBorderStyle: 'solid',
      cellCornerRadiusPx: 0,
      headerBarRadiusPx: 8,
      eventBg: '#f1f5f9',
      shabbatBg: '#fafaf9',
      todayBg: '#eff6ff',
      canvasBorderColor: '#e2e8f0',
    }),
  },
  {
    id: 'mizrach',
    nameHe: 'עדות המזרח',
    blurbHe: 'טורקיז, זהב, מרוקאי־אנדלוסי',
    previewCss: 'linear-gradient(135deg,#0d9488 0%,#14b8a6 35%,#ca8a04 100%)',
    cellBorder: 'thin',
    patch: patch({
      fontFamily: SERIF_STACK,
      fontWeight: 700,
      headerBarBg: 'linear-gradient(90deg,#115e59 0%,#0f766e 50%,#0d9488 100%)',
      headerBarBorderColor: '#ca8a04',
      headerBarTitleColor: '#fefce8',
      headerBarSubtitleColor: '#ccfbf1',
      headerHebMonthBg: 'rgba(15,118,110,0.85)',
      headerHebMonthTextColor: '#fefce8',
      headerHebMonthBorderColor: '#facc15',
      headerGregMonthTextColor: '#fefce8',
      headerGregMonthBorderColor: '#facc15',
      headerGregMonthBg: 'rgba(15,118,110,0.5)',
      calendarCanvasFill: '#ecfdf5',
      gridShellBg: 'rgba(240,253,250,0.95)',
      gridBorderColor: '#2dd4bf',
      gridWeekdayHeaderBg: '#ccfbf1',
      gridWeekdayHeaderTextColor: '#134e4a',
      gridWeekdayHeaderBorderBottomColor: '#14b8a6',
      cellBorderWidthPx: 1,
      cellBorderColor: '#99f6e4',
      cellBorderStyle: 'solid',
      cellCornerRadiusPx: 4,
      eventBg: '#cffafe',
      shabbatBg: '#fef9c3',
      todayBg: '#e0f2fe',
      canvasBorderColor: '#0d9488',
    }),
  },
  {
    id: 'chassidic',
    nameHe: 'חסידי',
    blurbHe: 'כחול עמוק, זהב, כבד',
    previewCss: 'linear-gradient(160deg,#1e3a5f 0%,#312e81 50%,#ca8a04 100%)',
    cellBorder: 'double',
    patch: patch({
      headerLayoutStyle: 'right_block',
      fontFamily: CLASSIC_STACK,
      fontWeight: 700,
      headerBarBg: 'linear-gradient(180deg,#1e293b 0%,#312e81 100%)',
      headerBarBorderColor: '#ca8a04',
      headerBarTitleColor: '#fefce8',
      headerBarSubtitleColor: '#cbd5e1',
      headerHebMonthBg: 'rgba(30,41,59,0.9)',
      headerHebMonthTextColor: '#fef08a',
      headerHebMonthBorderColor: '#eab308',
      headerGregMonthTextColor: '#fefce8',
      headerGregMonthBorderColor: '#eab308',
      calendarCanvasFill: '#0f172a',
      gridShellBg: 'rgba(30,41,59,0.92)',
      gridBorderColor: '#64748b',
      gridWeekdayHeaderBg: '#1e293b',
      gridWeekdayHeaderTextColor: '#e2e8f0',
      gridWeekdayHeaderBorderBottomColor: '#ca8a04',
      cellBorderWidthPx: 2,
      cellBorderColor: '#94a3b8',
      cellBorderStyle: 'double',
      cellCornerRadiusPx: 0,
      eventBg: '#dbeafe',
      shabbatBg: '#ffedd5',
      todayBg: '#e0e7ff',
      canvasBorderColor: '#ca8a04',
    }),
  },
  {
    id: 'family_fun',
    nameHe: 'ילדים / משפחתי',
    blurbHe: 'צבעוני, פינות מעוגלות',
    previewCss: 'linear-gradient(120deg,#fef08a 0%,#fda4af 40%,#93c5fd 100%)',
    cellBorder: 'rounded',
    patch: patch({
      headerLayoutStyle: 'centered_pill',
      fontFamily: SANS_STACK,
      fontWeight: 700,
      headerBarBg: 'linear-gradient(90deg,#fef9c3 0%,#fce7f3 50%,#dbeafe 100%)',
      headerBarBorderColor: '#f472b6',
      headerBarTitleColor: '#7c2d12',
      headerBarSubtitleColor: '#c2410c',
      headerHebMonthBg: '#ffffff',
      headerHebMonthBorderColor: '#38bdf8',
      headerGregMonthBorderColor: '#f472b6',
      calendarCanvasFill: '#fffbeb',
      gridShellBg: 'rgba(255,255,255,0.95)',
      gridBorderColor: '#fbbf24',
      gridWeekdayHeaderBg: '#fef3c7',
      gridWeekdayHeaderTextColor: '#9a3412',
      gridWeekdayHeaderBorderBottomColor: '#fb923c',
      cellBorderWidthPx: 2,
      cellBorderColor: '#fcd34d',
      cellBorderStyle: 'solid',
      cellCornerRadiusPx: 16,
      headerBarRadiusPx: 24,
      eventBg: '#dbeafe',
      shabbatBg: '#fef9c3',
      todayBg: '#fce7f3',
      canvasBorderColor: '#f472b6',
    }),
  },
  {
    id: 'wall_old',
    nameHe: 'לוח קיר ישן',
    blurbHe: 'כותרות גדולות, מינימום גרפיקה',
    previewCss: 'linear-gradient(180deg,#f8fafc 0%,#e2e8f0 100%)',
    cellBorder: 'thin',
    patch: patch({
      headerLayoutStyle: 'seamless',
      fontFamily: CLASSIC_STACK,
      fontWeight: 700,
      headerBarHeightPx: 92,
      headerHebMonthFontPx: 28,
      headerGregMonthFontPx: 18,
      gregDayFontPx: 18,
      hebDayFontPx: 18,
      eventTitleFontPx: 14,
      shabbatTimesFontPx: 12,
      headerBarBg: '#f1f5f9',
      headerBarBorderColor: '#64748b',
      headerBarTitleColor: '#0f172a',
      headerBarSubtitleColor: '#475569',
      headerHebMonthBg: '#ffffff',
      headerHebMonthBorderWidthPx: 1,
      calendarCanvasFill: '#f8fafc',
      gridShellBg: '#ffffff',
      gridBorderWidthPx: 1,
      gridBorderColor: '#cbd5e1',
      gridWeekdayHeaderBg: '#e2e8f0',
      gridWeekdayHeaderFontPx: 15,
      gridWeekdayHeaderTextColor: '#0f172a',
      cellBorderWidthPx: 1,
      cellBorderColor: '#94a3b8',
      cellBorderStyle: 'solid',
      cellCornerRadiusPx: 0,
      eventBg: '#e2e8f0',
      shabbatBg: '#fef3c7',
      todayBg: '#dbeafe',
      canvasBorderColor: '#64748b',
    }),
  },
  {
    id: 'nature_il',
    nameHe: 'טבע ארץ־ישראלי',
    blurbHe: 'ירוק־חום, אדמה ושמיים',
    previewCss: 'linear-gradient(180deg,#ecfccb 0%,#86efac 40%,#4d7c0f 100%)',
    cellBorder: 'thin',
    patch: patch({
      fontFamily: SANS_STACK,
      fontWeight: 600,
      headerBarBg: 'linear-gradient(90deg,#ecfccb 0%,#d9f99d 100%)',
      headerBarBorderColor: '#4d7c0f',
      headerBarTitleColor: '#14532d',
      headerBarSubtitleColor: '#3f6212',
      headerHebMonthBg: 'rgba(255,255,255,0.92)',
      headerHebMonthBorderColor: '#65a30d',
      calendarCanvasFill: '#f7fee7',
      gridShellBg: 'rgba(255,255,255,0.88)',
      gridBorderColor: '#84cc16',
      gridWeekdayHeaderBg: '#ecfccb',
      gridWeekdayHeaderTextColor: '#365314',
      gridWeekdayHeaderBorderBottomColor: '#a3e635',
      cellBorderWidthPx: 1,
      cellBorderColor: '#bbf7d0',
      cellBorderStyle: 'solid',
      cellCornerRadiusPx: 6,
      eventBg: '#dbeafe',
      shabbatBg: '#fef9c3',
      todayBg: '#dcfce7',
      canvasBorderColor: '#4d7c0f',
    }),
  },
  {
    id: 'dark_mode',
    nameHe: 'מצב לילה',
    blurbHe: 'רקע כהה, ניגודיות גבוהה',
    previewCss: 'linear-gradient(180deg,#020617 0%,#1e293b 100%)',
    cellBorder: 'thin',
    patch: patch({
      fontFamily: SANS_STACK,
      fontWeight: 600,
      headerBarBg: 'linear-gradient(180deg,#0f172a 0%,#1e293b 100%)',
      headerBarBorderColor: '#334155',
      headerBarTitleColor: '#f8fafc',
      headerBarSubtitleColor: '#94a3b8',
      headerHebMonthBg: 'rgba(15,23,42,0.9)',
      headerHebMonthTextColor: '#f8fafc',
      headerHebMonthBorderColor: '#475569',
      headerGregMonthTextColor: '#f8fafc',
      headerGregMonthBorderColor: '#64748b',
      headerGregMonthBg: 'rgba(30,41,59,0.6)',
      calendarCanvasFill: '#020617',
      gridShellBg: 'rgba(15,23,42,0.85)',
      gridBorderColor: '#334155',
      gridWeekdayHeaderBg: '#1e293b',
      gridWeekdayHeaderTextColor: '#e2e8f0',
      gridWeekdayHeaderBorderBottomColor: '#475569',
      cellBorderWidthPx: 1,
      cellBorderColor: '#334155',
      cellBorderStyle: 'solid',
      cellCornerRadiusPx: 6,
      eventBg: '#c7d2fe',
      shabbatBg: '#fde68a',
      todayBg: '#bae6fd',
      canvasBorderColor: '#475569',
    }),
  },
  {
    id: 'executive',
    nameHe: 'יוקרתי',
    blurbHe: 'שחור, אפור, זהב',
    previewCss: 'linear-gradient(135deg,#0a0a0a 0%,#27272a 40%,#ca8a04 100%)',
    cellBorder: 'thin',
    patch: patch({
      headerLayoutStyle: 'right_block',
      fontFamily: SANS_STACK,
      fontWeight: 600,
      headerBarBg: 'linear-gradient(90deg,#09090b 0%,#18181b 100%)',
      headerBarBorderColor: '#ca8a04',
      headerBarTitleColor: '#fafaf9',
      headerBarSubtitleColor: '#a1a1aa',
      headerHebMonthBg: 'rgba(24,24,27,0.95)',
      headerHebMonthTextColor: '#fef08a',
      headerHebMonthBorderColor: '#eab308',
      headerGregMonthTextColor: '#fafaf9',
      headerGregMonthBorderColor: '#a16207',
      calendarCanvasFill: '#fafafa',
      gridShellBg: 'rgba(255,255,255,0.95)',
      gridBorderColor: '#d4d4d8',
      gridWeekdayHeaderBg: '#f4f4f5',
      gridWeekdayHeaderTextColor: '#18181b',
      gridWeekdayHeaderBorderBottomColor: '#ca8a04',
      cellBorderWidthPx: 1,
      cellBorderColor: '#d4d4d8',
      cellBorderStyle: 'solid',
      cellCornerRadiusPx: 4,
      eventBg: '#e0e7ff',
      shabbatBg: '#fef9c3',
      todayBg: '#e4e4e7',
      canvasBorderColor: '#27272a',
    }),
  },
  {
    id: 'watercolor',
    nameHe: 'אקוורל',
    blurbHe: 'כתמי צבע עדינים',
    previewCss: 'linear-gradient(120deg,#e0f2fe 0%,#fce7f3 50%,#fef3c7 100%)',
    cellBorder: 'rounded',
    patch: patch({
      headerLayoutStyle: 'centered_pill',
      fontFamily: SERIF_STACK,
      fontWeight: 600,
      headerBarBg: 'linear-gradient(120deg,#f0f9ff 0%,#fdf2f8 100%)',
      headerBarBorderColor: '#7dd3fc',
      headerBarTitleColor: '#0c4a6e',
      headerBarSubtitleColor: '#0369a1',
      headerHebMonthBg: 'rgba(255,255,255,0.85)',
      headerHebMonthBorderColor: '#f9a8d4',
      calendarCanvasFill: '#f8fafc',
      gridShellBg: 'rgba(255,255,255,0.75)',
      gridBorderColor: '#bae6fd',
      gridWeekdayHeaderBg: '#e0f2fe',
      gridWeekdayHeaderTextColor: '#0c4a6e',
      gridWeekdayHeaderBorderBottomColor: '#7dd3fc',
      cellBorderWidthPx: 1,
      cellBorderColor: '#e0e7ff',
      cellBorderStyle: 'solid',
      cellCornerRadiusPx: 14,
      headerBarRadiusPx: 22,
      eventBg: '#e0f2fe',
      shabbatBg: '#fef3c7',
      todayBg: '#fce7f3',
      canvasBorderColor: '#93c5fd',
    }),
  },
  {
    id: 'handwriting',
    nameHe: 'כתב יד',
    blurbHe: 'פונט כתב יד, רקע דף',
    previewCss: 'linear-gradient(180deg,#fffef7 0%,#fefce8 50%,#fef9c3 100%)',
    cellBorder: 'rounded',
    patch: patch({
      fontFamily: HAND_STACK,
      fontWeight: 600,
      headerBarBg: 'repeating-linear-gradient(0deg,#fffbeb,#fffbeb 23px,#fef3c7 23px,#fef3c7 24px)',
      headerBarBorderColor: '#d6d3d1',
      headerBarTitleColor: '#44403c',
      headerBarSubtitleColor: '#78716c',
      headerHebMonthBg: 'rgba(255,255,255,0.9)',
      headerHebMonthBorderColor: '#a8a29e',
      calendarCanvasFill: '#fffbeb',
      gridShellBg: 'rgba(255,253,245,0.92)',
      gridBorderColor: '#d6d3d1',
      gridWeekdayHeaderBg: '#fef3c7',
      gridWeekdayHeaderTextColor: '#57534e',
      gridWeekdayHeaderBorderBottomColor: '#d6d3d1',
      cellBorderWidthPx: 1,
      cellBorderColor: '#e7e5e4',
      cellBorderStyle: 'solid',
      cellCornerRadiusPx: 10,
      eventBg: '#e0f2fe',
      shabbatBg: '#ffedd5',
      todayBg: '#fef08a',
      canvasBorderColor: '#a8a29e',
    }),
  },
];

const PRESERVE_KEYS: (keyof CalendarSettings)[] = [
  'titleMain',
  'titleSub',
  'backgroundImageDataUrl',
  'backgroundImagesByMonth',
  'backgroundImageMode',
  'backgroundOpacity',
  'enableManualEdits',
  'showEditButtonInCells',
  'showParsha',
  'shabbatTimesSource',
  'zmanimCity',
  'candleLightingMins',
  'fastTzaitStyle',
  'fastSunsetOffsetMins',
  'pdfPagePreset',
  'pdfOrientation',
  'pdfCustomWidthMm',
  'pdfCustomHeightMm',
  'pdfMarginMm',
  'pdfHtml2CanvasScale',
  'pdfExportCellHeightPx',
  'calendarLayoutScalePercent',
  'canvasPaddingPx',
  'canvasPaddingTopPx',
];

function pickPreserved(current: CalendarSettings): Partial<CalendarSettings> {
  const out: Partial<CalendarSettings> = {};
  for (const k of PRESERVE_KEYS) {
    (out as Record<string, unknown>)[k as string] = current[k];
  }
  return out;
}

export function applyDesignThemeId(current: CalendarSettings, themeId: string): CalendarSettings {
  if (themeId === 'default') {
    return {
      ...DEFAULT_SETTINGS,
      ...pickPreserved(current),
      designThemeId: 'default',
    } as CalendarSettings;
  }
  const entry = CALENDAR_THEME_CATALOG.find((t) => t.id === themeId);
  if (!entry) {
    return { ...DEFAULT_SETTINGS, ...pickPreserved(current), designThemeId: 'default' };
  }
  return {
    ...DEFAULT_SETTINGS,
    ...entry.patch,
    ...pickPreserved(current),
    designThemeId: themeId,
  } as CalendarSettings;
}

export function getThemeEntry(themeId: string): CalendarThemeCatalogEntry | undefined {
  return CALENDAR_THEME_CATALOG.find((t) => t.id === themeId);
}
